### PR TITLE
Vault enhancements

### PR DESCRIPTION
**Pull request by AssafMiron**
### Desired Outcome

* Fixing issues is Firewall checks
* Fixing issues in NIC testing
* Fixing miscellaneous issues

### Connected Issue/Story

Resolves #[relevant GitHub issue(s), e.g. 76]

#### Changelog

- [X] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Documentation

- [X] This PR does not require updating any documentation

#### Behavior

- [X] This PR changes product behavior and has been reviewed by a PO - Windows 2019 NIC hardening is different than other OS

### CODE REVIEW

**Comment by AssafMiron** [comment]
@ediulia I have added more fixes based on your testing - would be great if you can verify them
Thanks!

**Comment by ediulia** [comment]
Hey @AssafMiron

**VaultHardeningSteps.psm1**
I would recommend replacing **the**:
ForEach ($rule in $($FWRules | Where-Object { $_.DisplayGroup -match "NON_STD" }))
**with**:
ForEach ($rule in $($FWRules | Where-Object { ($_.DisplayGroup -match "NON_STD") -or ($_.DisplayGroup -NotMatch "CYBERARK_") }))

**CommonUtil.psm1**
Looks like you merged back the Write-LogMessage typos of "Advance Audit" , I fixed all the typos to "Advanced Audit" in previous PRs

I have the next exceptions applied on the Vault hardening 

First in Windows2019Security.inf file:
"WinRM",2,""
SeRemoteInteractiveLogonRight = *S-1-5-32-544

Second:
I have 2 local Users created and added to the administrators group

Looks like the Script doesn't catch those exceptions on the Vault

**Comment by ediulia** [comment]
@AssafMiron
VaultHardeningSteps.psm1

We need to review the Call for Compare-AmountOfUserPermissions function in line 726 , looks like it copied from CPM hardening. And maybe to add some recommendation reference for keys NTFS recommended permissions

**Comment by AssafMiron** [comment]
@ediulia merged back all fixes, including the one you solved about Error 57
Please take the changes from this branch and test if you can - Thanks!

**Pull request merged**
